add missing parentheses
addressing:
  File "/usr/lib/python2.6/site-packages/tito/distributionbuilder.py", line 26, in patch_upstream
    % self.rpmbuild_gitcopy, self.project_name, self.upstream_version, self.build_version, self.git_commit_id)
TypeError: not enough arguments for format string