make version comparison compat with python2 and python3
Alas, python3 doesn't have the cmp() function.

Support both python2 and python3 for comparisons using tip from
https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons

Avoids TB on python3:

    ======================================================================
    ERROR: test_compare_version (unit.common-tests.ExtractBugzillasTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/sandbox/test/unit/common-tests.py", line 224, in test_compare_version
        self.assertEquals(0, compare_version("1", "1"))
      File "/home/sandbox/src/tito/common.py", line 689, in compare_version
        return cmp(normalize(version1), normalize(version2))
    NameError: global name 'cmp' is not defined