do not fail if spec does not have any source
addressing:
Error running command: /usr/bin/spectool --list-files '/tmp/tito-build/rpmbuild-ruby193-d6e54d8c72c34196a4f51ac134c4172b44d9eccae0bLpW/SOURCES/ruby193-1/ruby193.spec' | awk '{print $2}' |xargs -l1 basename
Status code: 31488
Command output: basename: missing operand
Try 'basename --help' for more information.
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 94, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 401, in main
    return builder.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/builder.py", line 194, in run
    self.srpm()
  File "/usr/lib/python2.7/site-packages/tito/builder.py", line 228, in srpm
    self.tgz()
  File "/usr/lib/python2.7/site-packages/tito/builder.py", line 479, in tgz
    result = run_command(cmd)
  File "/usr/lib/python2.7/site-packages/tito/common.py", line 217, in run_command
    raise Exception("Error running command")
Exception: Error running command