add missing import of commands
addressing:
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 94, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 638, in main
    scratch=self.options.scratch)
  File "/usr/lib/python2.7/site-packages/tito/release.py", line 490, in release
    self._git_release()
  File "/usr/lib/python2.7/site-packages/tito/release.py", line 507, in _git_release
    self.builder.tgz()
  File "/usr/lib/python2.7/site-packages/tito/builder.py", line 784, in tgz
    self.patch_upstream()
  File "/usr/lib/python2.7/site-packages/tito/distributionbuilder.py", line 34, in patch_upstream
    (status, output) = commands.getstatusoutput(
NameError: global name 'commands' is not defined