if we grep rpmbuild output for some string, we have to switch to C locale
addressing:
WARNING: rpmbuild directory already exists, removing...
Building package [spacewalk-config-1.2.2-1]
Wrote: /tmp/tito/spacewalk-config-1.2.2.tar.gz
Zapsáno: /tmp/tito/spacewalk-config-1.2.2-1.fc13.src.rpm

ERROR: Unable to locate 'Wrote: ' lines in rpmbuild output