_update_package_metadata() does not allwo release parameter no more
this is left over after commit 7c3c04f7
Release type is now handled by overriden release_type() method.

addressing:
Traceback (most recent call last):
  File "/usr/bin/tito", line 23, in <module>
    CLI().main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 98, in main
    return module.main(argv)
  File "/usr/lib/python2.7/site-packages/tito/cli.py", line 515, in main
    return tagger.run(self.options)
  File "/usr/lib/python2.7/site-packages/tito/tagger.py", line 96, in run
    self._tag_release()
  File "/usr/lib/python2.7/site-packages/tito/zstreamtagger.py", line 20, in _tag_release
    self._update_package_metadata(new_version, release=True)
TypeError: _update_package_metadata() got an unexpected keyword argument 'release'